import {
  Transaction,
  TransactionStatus,
  TransactionType,
} from "../types/transaction.types";
import { AnomalyResult, AnomalySeverity } from "../types/anomaly.types";
import { ClientRegistry } from "../types/client.types";

// Mock Transactions
export const mockTransactions: Transaction[] = [
  {
    id: "1",
    transaction_id: "TXN001",
    transaction_hash: "0x1234567890abcdef1234567890abcdef12345678",
    transaction_type: TransactionType.DEPOSIT,
    amount: 150000,
    currency: "INR",
    transaction_timestamp: "2024-07-24T10:30:00Z",
    transaction_status: TransactionStatus.COMPLETED,
    on_chain_status: "confirmed",
    from_account: "ACC001",
    to_account: "ACC002",
    from_wallet_address: "0xabcd1234...",
    to_wallet_address: "0xefgh5678...",
    client_id: "CLI001",
    client_name: "Acme Corp",
    blockchain_network: "Hyperledger Fabric",
    ledger_type: "Permissioned",
    chain_id: 1,
    block_number: 12345,
    gas_fee: 0.005,
    created_at: "2024-07-24T10:30:00Z",
    updated_at: "2024-07-24T10:35:00Z",
  },
  {
    id: "2",
    transaction_id: "TXN002",
    transaction_hash: "0x2234567890abcdef1234567890abcdef12345679",
    transaction_type: TransactionType.WITHDRAWAL,
    amount: 500000,
    currency: "INR",
    transaction_timestamp: "2024-07-24T11:15:00Z",
    transaction_status: TransactionStatus.PENDING,
    on_chain_status: "pending",
    from_account: "ACC003",
    to_account: "ACC004",
    from_wallet_address: "0xijkl9012...",
    to_wallet_address: "0xmnop3456...",
    client_id: "CLI002",
    client_name: "TechStart Inc",
    blockchain_network: "Hyperledger Fabric",
    ledger_type: "Permissioned",
    chain_id: 1,
    block_number: 12346,
    gas_fee: 0.008,
    created_at: "2024-07-24T11:15:00Z",
    updated_at: "2024-07-24T11:15:00Z",
  },
  {
    id: "3",
    transaction_id: "TXN003",
    transaction_hash: "0x3334567890abcdef1234567890abcdef12345680",
    transaction_type: TransactionType.TRANSFER,
    amount: 1000000,
    currency: "INR",
    transaction_timestamp: "2024-07-24T12:00:00Z",
    transaction_status: TransactionStatus.COMPLETED,
    on_chain_status: "confirmed",
    from_account: "ACC005",
    to_account: "ACC006",
    from_wallet_address: "0xqrst7890...",
    to_wallet_address: "0xuvwx1234...",
    client_id: "CLI003",
    client_name: "Global Finance Ltd",
    blockchain_network: "Hyperledger Fabric",
    ledger_type: "Permissioned",
    chain_id: 1,
    block_number: 12347,
    gas_fee: 0.012,
    created_at: "2024-07-24T12:00:00Z",
    updated_at: "2024-07-24T12:05:00Z",
  },
];

// Mock Anomalies
export const mockAnomalies: AnomalyResult[] = [
  {
    anomalyId: "ANO001",
    transactionId: "TXN002",
    transactionHash: "0x2234567890abcdef1234567890abcdef12345679",
    clientId: "CLI002",
    amount: 500000,
    currency: "INR",
    fromAccount: "ACC003",
    toAccount: "ACC004",
    fromWalletAddress: "0xijkl9012...",
    toWalletAddress: "0xmnop3456...",
    transactionType: TransactionType.WITHDRAWAL,
    anomalyScore: 0.85,
    severity: AnomalySeverity.HIGH,
    anomalyCategory: "FRAUD",
    anomalyTypes: ["Unusual Amount", "Suspicious Pattern"],
    anomalyReasons: [
      {
        reasonCode: "AMT_THRESHOLD",
        description: "Transaction amount exceeds normal threshold by 300%",
      },
      {
        reasonCode: "VELOCITY_CHECK",
        description: "Multiple large transactions in short time window",
      },
    ],
    confidence: 0.92,
    modelName: "Isolation Forest + Autoencoder",
    modelVersion: "v1.2.0",
    reviewStatus: "UNDER_REVIEW",
    assignedTo: "analyst@example.com",
    caseId: "CASE001",
    detectedAt: "2024-07-24T11:16:00Z",
    createdAt: "2024-07-24T11:16:00Z",
    updatedAt: "2024-07-24T11:16:00Z",
  },
  {
    anomalyId: "ANO002",
    transactionId: "TXN003",
    transactionHash: "0x3334567890abcdef1234567890abcdef12345680",
    clientId: "CLI003",
    amount: 1000000,
    currency: "INR",
    fromAccount: "ACC005",
    toAccount: "ACC006",
    fromWalletAddress: "0xqrst7890...",
    toWalletAddress: "0xuvwx1234...",
    transactionType: TransactionType.TRANSFER,
    anomalyScore: 0.65,
    severity: AnomalySeverity.MEDIUM,
    anomalyCategory: "RISK",
    anomalyTypes: ["Large Transfer"],
    anomalyReasons: [
      {
        reasonCode: "LARGE_TXN",
        description: "Transaction amount is significantly higher than average",
      },
    ],
    confidence: 0.78,
    modelName: "Isolation Forest + Autoencoder",
    modelVersion: "v1.2.0",
    reviewStatus: "PENDING",
    assignedTo: null,
    caseId: null,
    detectedAt: "2024-07-24T12:01:00Z",
    createdAt: "2024-07-24T12:01:00Z",
    updatedAt: "2024-07-24T12:01:00Z",
  },
];

// Mock Clients
export const mockClients: ClientRegistry[] = [
  {
    client_id: "CLI001",
    client_name: "Acme Corp",
    client_type: "Corporate",
    lei: "529900HNOAA1KXQJUQ27",
    industry_sector: "Technology",
    country_of_incorporation: "India",
    risk_tier: "Low",
    relationship_manager: "John Doe",
    wallet_address: "0xabcd1234...",
    wallet_type: "Corporate",
    facility_type: "Credit Line",
    credit_limit: 5000000,
    daily_deposit_limit: 1000000,
    daily_withdrawal_limit: 500000,
    expected_activity_window: "09:00-18:00",
    authorized_signatories: ["Alice Johnson", "Bob Smith"],
    kyc_status: "Verified",
    aml_status: "Clear",
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-07-20T00:00:00Z",
  },
  {
    client_id: "CLI002",
    client_name: "TechStart Inc",
    client_type: "Startup",
    lei: "529900HNOAA1KXQJUQ28",
    industry_sector: "Fintech",
    country_of_incorporation: "India",
    risk_tier: "Medium",
    relationship_manager: "Jane Smith",
    wallet_address: "0xijkl9012...",
    wallet_type: "Business",
    facility_type: "Overdraft",
    credit_limit: 2000000,
    daily_deposit_limit: 500000,
    daily_withdrawal_limit: 300000,
    expected_activity_window: "08:00-20:00",
    authorized_signatories: ["Charlie Brown"],
    kyc_status: "Verified",
    aml_status: "Under Review",
    created_at: "2024-03-10T00:00:00Z",
    updated_at: "2024-07-22T00:00:00Z",
  },
  {
    client_id: "CLI003",
    client_name: "Global Finance Ltd",
    client_type: "Enterprise",
    lei: "529900HNOAA1KXQJUQ29",
    industry_sector: "Banking",
    country_of_incorporation: "India",
    risk_tier: "High",
    relationship_manager: "Sarah Williams",
    wallet_address: "0xqrst7890...",
    wallet_type: "Enterprise",
    facility_type: "Term Loan",
    credit_limit: 10000000,
    daily_deposit_limit: 2000000,
    daily_withdrawal_limit: 1000000,
    expected_activity_window: "24/7",
    authorized_signatories: ["David Lee", "Emma Davis", "Frank Wilson"],
    kyc_status: "Verified",
    aml_status: "Clear",
    created_at: "2024-02-20T00:00:00Z",
    updated_at: "2024-07-23T00:00:00Z",
  },
];

// Helper function to generate additional mock transactions
export function generateMockTransactions(count: number): Transaction[] {
  const types = Object.values(TransactionType);
  const statuses = Object.values(TransactionStatus);
  const transactions: Transaction[] = [];

  for (let i = 0; i < count; i++) {
    const type = types[Math.floor(Math.random() * types.length)];
    const status = statuses[Math.floor(Math.random() * statuses.length)];
    const amount = Math.floor(Math.random() * 1000000) + 10000;

    transactions.push({
      id: `${i + 4}`,
      transaction_id: `TXN${String(i + 4).padStart(3, "0")}`,
      transaction_hash: `0x${Math.random().toString(16).substring(2, 42)}`,
      transaction_type: type,
      amount,
      currency: "INR",
      transaction_timestamp: new Date(
        Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000
      ).toISOString(),
      transaction_status: status,
      on_chain_status: status === TransactionStatus.COMPLETED ? "confirmed" : "pending",
      from_account: `ACC${String(Math.floor(Math.random() * 100)).padStart(3, "0")}`,
      to_account: `ACC${String(Math.floor(Math.random() * 100)).padStart(3, "0")}`,
      from_wallet_address: `0x${Math.random().toString(16).substring(2, 12)}...`,
      to_wallet_address: `0x${Math.random().toString(16).substring(2, 12)}...`,
      client_id: `CLI${String(Math.floor(Math.random() * 10) + 1).padStart(3, "0")}`,
      client_name: `Client ${i + 4}`,
      blockchain_network: "Hyperledger Fabric",
      ledger_type: "Permissioned",
      chain_id: 1,
      block_number: 12345 + i,
      gas_fee: Math.random() * 0.02,
      created_at: new Date(
        Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000
      ).toISOString(),
      updated_at: new Date().toISOString(),
    });
  }

  return transactions;
}
